### PR TITLE
Texas testing

### PR DESCRIPTION
**Pull request by rien88**

### CODE REVIEW

**Review by gus-robotics88 — CHANGES_REQUESTED** [review]
I did notice that this made any bag topic record only at a maximum of 10 hz. We probably want to up this to the highest frequency topic we might care about. I'm not sure what that might be, maybe like 50hz or something?

**Comment by rien88** [comment]
> I did notice that this made any bag topic record only at a maximum of 10 hz. We probably want to up this to the highest frequency topic we might care about. I'm not sure what that might be, maybe like 50hz or something?

How did you conclude that 10Hz is the max? I see several topics recording at higher than 10 Hz. E.g. I have ~130 Hz for /mavros/imu/data and ~60 Hz for /tf

**Comment by gus-robotics88** [comment]
> > I did notice that this made any bag topic record only at a maximum of 10 hz. We probably want to up this to the highest frequency topic we might care about. I'm not sure what that might be, maybe like 50hz or something?
> 
> How did you conclude that 10Hz is the max? I see several topics recording at higher than 10 Hz. E.g. I have ~130 Hz for /mavros/imu/data and ~60 Hz for /tf

Oh really? Interesting. When i look at the bag files with `rosrun rqt_bag rqt_bag`, none of the topics appear to be recorded at any frequency higher than 10hz (from just looking at the published topics). Were you getting the frequency from rostopic hz while replaying the bag?

**Comment by rien88** [comment]
> > > I did notice that this made any bag topic record only at a maximum of 10 hz. We probably want to up this to the highest frequency topic we might care about. I'm not sure what that might be, maybe like 50hz or something?
> > 
> > 
> > How did you conclude that 10Hz is the max? I see several topics recording at higher than 10 Hz. E.g. I have ~130 Hz for /mavros/imu/data and ~60 Hz for /tf
> 
> Oh really? Interesting. When i look at the bag files with `rosrun rqt_bag rqt_bag`, none of the topics appear to be recorded at any frequency higher than 10hz (from just looking at the published topics). Were you getting the frequency from rostopic hz while replaying the bag?

Yep, I checked with rostopic hz while replaying

**Comment by gus-robotics88** [comment]
> > > > I did notice that this made any bag topic record only at a maximum of 10 hz. We probably want to up this to the highest frequency topic we might care about. I'm not sure what that might be, maybe like 50hz or something?
> > > 
> > > 
> > > How did you conclude that 10Hz is the max? I see several topics recording at higher than 10 Hz. E.g. I have ~130 Hz for /mavros/imu/data and ~60 Hz for /tf
> > 
> > 
> > Oh really? Interesting. When i look at the bag files with `rosrun rqt_bag rqt_bag`, none of the topics appear to be recorded at any frequency higher than 10hz (from just looking at the published topics). Were you getting the frequency from rostopic hz while replaying the bag?
> 
> Yep, I checked with rostopic hz while replaying

Hmm. Could you try a rostopic echo on /mavros/imu/data and see if it visually looks like it is coming out at 130 Hz? It should be easy to tell if it's printing super fast or looks like it's only being sent back at 10hz

**Comment by gus-robotics88** [comment]
> > > > I did notice that this made any bag topic record only at a maximum of 10 hz. We probably want to up this to the highest frequency topic we might care about. I'm not sure what that might be, maybe like 50hz or something?
> > > 
> > > 
> > > How did you conclude that 10Hz is the max? I see several topics recording at higher than 10 Hz. E.g. I have ~130 Hz for /mavros/imu/data and ~60 Hz for /tf
> > 
> > 
> > Oh really? Interesting. When i look at the bag files with `rosrun rqt_bag rqt_bag`, none of the topics appear to be recorded at any frequency higher than 10hz (from just looking at the published topics). Were you getting the frequency from rostopic hz while replaying the bag?
> 
> Yep, I checked with rostopic hz while replaying

Ahh. So for some reason, rostopic hz says /mavros/imu/data is getting published at 130hz, but the data is not actually getting recorded at that rate. You can see this if you do rostopic echo /mavros/imu/data, and you'll see it's only returning data at 10hz.

**Comment by rien88** [comment]
> > > > > I did notice that this made any bag topic record only at a maximum of 10 hz. We probably want to up this to the highest frequency topic we might care about. I'm not sure what that might be, maybe like 50hz or something?
> > > > 
> > > > 
> > > > How did you conclude that 10Hz is the max? I see several topics recording at higher than 10 Hz. E.g. I have ~130 Hz for /mavros/imu/data and ~60 Hz for /tf
> > > 
> > > 
> > > Oh really? Interesting. When i look at the bag files with `rosrun rqt_bag rqt_bag`, none of the topics appear to be recorded at any frequency higher than 10hz (from just looking at the published topics). Were you getting the frequency from rostopic hz while replaying the bag?
> > 
> > 
> > Yep, I checked with rostopic hz while replaying
> 
> Ahh. So for some reason, rostopic hz says /mavros/imu/data is getting published at 130hz, but the data is not actually getting recorded at that rate. You can see this if you do rostopic echo /mavros/imu/data, and you'll see it's only returning data at 10hz.

Just updated the loop rate to 200 Hz, now when I do echo IMU it looks much faster. Can you pull and verify on your end?

**Review by gus-robotics88 — APPROVED** [review]

**Pull request merged**
